stolostron/governance-policy-framework-addon

sonar-project.properties
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
=> Set the SonarCloud properties

.github/workflows/kind.yml, README.md, controllers/templatesync/template_sync.go, test/e2e/case4_status_merge_test.go
Applied cleanly for me `¯\_(ツ)_/¯`
Closes https://github.com/stolostron/governance-policy-framework-addon/issues/14
=> Sync from upstream #18

.github/workflows/kind.yml, Makefile
Cherry pick from upstream:
- https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/19
Closes #16
=> Upstream sync: Set "minimum" tag in Makefile

controllers/templatesync/template_sync.go, deploy/operator.yaml, deploy/rbac/role.yaml, test/e2e/case16_restore_owner_refs_test.go, test/resources/case16_restore_owner_refs/case16-patch-configpolicy.yaml, test/resources/case16_restore_owner_refs/case16-test-policy.yaml
closes https://github.com/stolostron/governance-policy-framework-addon/issues/35
=> Manual sync of PRs #30-32, 34

go.mod, go.sum, main.go
Manual sync:
* open-cluster-management-io/governance-policy-framework-addon#41
=> Manual cherry-pick (#41)

.github/workflows/kind.yml, Makefile, controllers/gatekeepersync/gatekeeper_constraint_sync.go, controllers/secretsync/secret_sync.go, controllers/specsync/policy_spec_sync.go, controllers/statussync/policy_status_sync.go, controllers/templatesync/template_sync.go, controllers/templatesync/template_sync_test.go, controllers/uninstall/triggeruninstall.go, controllers/uninstall/watcher.go, deploy/operator.yaml, deploy/rbac/role.yaml, go.mod, go.sum, main.go, main_test.go, test/e2e/case10_error_test.go, test/e2e/case17_gatekeeper_sync_test.go, test/e2e/case18_uninstall_test.go, test/e2e/case19_gatekeeper_disable_test.go, test/e2e/e2e_suite_test.go, test/resources/case10_template_sync_error_test/multiple-obj-template-arrays.yaml, test/resources/case18_uninstall/case18-gk-policy-updated.yaml, test/resources/case18_uninstall/case18-gk-policy.yaml, test/resources/case19_gatekeeper_disable/case19-gk-policy.yaml, tool/options.go
Manual sync of:
* open-cluster-management-io/governance-policy-framework-addon#43
* open-cluster-management-io/governance-policy-framework-addon#44
* open-cluster-management-io/governance-policy-framework-addon#46
* open-cluster-management-io/governance-policy-framework-addon#47
* open-cluster-management-io/governance-policy-framework-addon#48
* open-cluster-management-io/governance-policy-framework-addon#49
Closes #68
=> Manual sync (#43, #44, #46, #47, #48, #49)

controllers/uninstall/watcher.go, deploy/manager/manager.yaml, deploy/operator.yaml, tool/options.go
Closes https://github.com/stolostron/governance-policy-framework-addon/issues/71
=> Manual Sync (#51)

controllers/templatesync/template_sync.go, controllers/utils/events.go, main.go, test/e2e/case16_restore_owner_refs_test.go
For https://issues.redhat.com/browse/ACM-5135
Adapted from changes for https://issues.redhat.com/browse/ACM-4699 (which has a clone called https://issues.redhat.com/browse/ACM-5318)
=> [release-2.7] fix pending state in some situations

Makefile
Manual cherry-pick:
- #141 
Ref: https://issues.redhat.com/browse/ACM-6966
=> [release-2.8] Fix Hosted mode framework test (#141)

.tekton/governance-policy-framework-addon-dfsa-pull-request.yaml, .tekton/governance-policy-framework-addon-dfsa-push.yaml, Dockerfile.rhtap
See the details in the associated task.
Refs:
- https://issues.redhat.com/browse/ACM-7178
=> Add rhtap dockerfile with allowed image references

go.mod, go.sum
=> [Manual Sync] Remove the requirement on k8s.io/client-go@v12.0.0+incompatible

go.mod, go.sum
=> [Manual Sync] Update the kubernetes-dependency-watches library

Dockerfile.rhtap
ref: https://issues.redhat.com/browse/ACM-9734
=> Update RHTAP Dockerfile to Go v1.21

go.mod, go.sum
Manual sync of:
- https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/124
Closes #312
=> [manual-sync] Address CVE-2024-24786

README.md
=> [release-2.8] Build refresh

controllers/statussync/policy_status_sync.go, controllers/templatesync/template_sync.go, test/e2e/case22_user_validation_error_test.go, test/resources/case22_user_validation_error/case22-test-correct.yaml, test/resources/case22_user_validation_error/case22-test-err.yaml
Manual cherry-pick:
- #150
- #210 
Ref: https://issues.redhat.com/browse/ACM-6803
=> [release-2.9] Backport fix for compliance on user errors

controllers/gatekeepersync/gatekeeper_constraint_sync.go, controllers/specsync/policy_spec_sync.go, controllers/statussync/policy_status_sync.go, controllers/templatesync/template_sync.go, main.go
Closes #326 
I skipped this PR:
https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/125
Let me know if some of it should have been pulled in @zyjjay.
=> Manual sync of upstream PRs: #126, #127

controllers/gatekeepersync/gatekeeper_constraint_sync.go, controllers/specsync/policy_spec_sync.go, controllers/statussync/policy_status_sync.go, controllers/templatesync/template_sync.go, main.go
Relates:
https://issues.redhat.com/browse/ACM-10694
https://issues.redhat.com/browse/ACM-10695
=> [2.9] Manual sync of upstream PRs: #126, #127

.tekton/governance-policy-framework-addon-acm-210-pull-request.yaml, .tekton/governance-policy-framework-addon-acm-210-push.yaml, build/Dockerfile, build/Dockerfile.rhtap
Also updates ubi8 --> ubi9
Contains changes from:
- #396 
ref: https://issues.redhat.com/browse/ACM-10739
=> [release-2.10] Use entitled Dockerfile for Konflux

controllers/templatesync/template_sync.go, controllers/templatesync/template_sync_test.go
=> [2.10 manual cherry-pick] Set the cluster namespace on OperatorPolicy dependencies

.tekton/governance-policy-framework-addon-acm-210-pull-request.yaml, .tekton/governance-policy-framework-addon-acm-210-push.yaml
This update configures the SAST task to upload SARIF results to quay.io for
long-term storage
Related: 
- https://issues.redhat.com/browse/KONFLUX-3663
- https://issues.redhat.com/browse/KONFLUX-2263
=> fix(KONFLUX-3663): format PipelineRun files and upload SAST results

.tekton/governance-policy-framework-addon-acm-214-push.yaml
Refs:
- https://issues.redhat.com/browse/ACM-20948
=> Add multiarch build to konflux pipeline
